---
layout: cv
title: Taylor Alvey's CV
---
# Taylor Alvey
Computer Enthusiast, Engineer, Scientist

<div id="webaddress">
<a href="taylor.alvey5@gmail.com">taylor.alvey5@gmail.com</a>
| <a href="https://docs.google.com/document/d/1TKS5fHqLyytoraWm03asFqvHHXetaYgQTZ59mb8x1P0/edit?usp=sharing">My Resume Document</a>
</div>


## Currently

Studing Computer Engineering

### Specialized in

Python, HTML, CSS, PHP, JavaScript, Pandas, JAVA, Machine Code, SQL.


### Research interests

Artificial Intelligence, Database Implementation, Computer Hardware, Website Applications.


## Education

`August 2019- May 2021`
__Pine View High School__

`September 2021 - May 2022`
__Utah State University__

- Undergraduate

`January 2025 - Now`
__Brigham Young University at Idaho__

- Undergraduate



## Awards

`2021`
Scholar, *Regents*, St. George, Utah

Academic All-American, *UHSAA*, St. George, Utah



## Projects

<a href="https://amhart02.github.io/musicportfolio/">Website Project</a>

<a href="http://mealplanning.altervista.org/">Recipe Database Project</a>

<!-- ### Journals

`1669`
Newton Sir I, De analysi per æquationes numero terminorum infinitas. 

`1669`
Lectiones opticæ.

etc. etc. etc. -->

<!-- ### Patents

`2012`
Infinitesimal calculus for solutions to physics problems, [SMBC](http://www.techdirt.com/articles/20121011/09312820678/if-patents-had-been-around-time-newton.shtml) patent 001
 -->

## Occupation

`2022`
__Panda Express__, St. George, Utah

- Front End Associate
- Served Food

`2024`
__Costco Wholesale__, St. George, Utah

- Bakery Organizational Specialist
- Wrapper and Baker

`2024`
__Melaleuca The Wellness Company__, Rexburg, Idaho

- Wellness Department
- Customer Service Call Center




### Footer

Last updated: April 2025